resources:
- oauth.yaml
- project-leaders.yaml
- self-provisioners.yaml
- clusteradmin.yaml

secretGenerator:
- name: htpasswd-secret
  namespace: openshift-config
  files:
  - htpasswd=./secret/htpasswd-secret-data

generatorOptions:
  disableNameSuffixHash: true
