apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: policy-config-oauth
placementBindingDefaults:
  name: binding-policy-openshift-dr-hub
policyDefaults:
  categories:
    - CM Configuration Management
  controls: 
    - CM-2 Baseline Configuration
  namespace: rhacm-policies
  policySets:
    - openshift-hub
    - openshift-clusters
    - openshift-prd
  remediationAction: enforce
  severity: medium
  standards:
    - NIST SP 800-53

policies:
  - name: policy-oauth
    categories:
      - SI System and Information Integrity
    controls:
      - SI-7 Software Firmware and Information Integrity
    manifests:
      - path: playbooks/clusteradmin.yaml
      - path: playbooks/oauth.yaml
      - path: playbooks/group-ocp-administradores.yaml
      - path: playbooks/group-ocp-project-leaders.yaml
      - path: playbooks/self-provisioners.yaml
    standards:
      - NIST SP 800-53
    policySets:
      - openshift-hub

policySets:
  - description: Aplica políticas para configurar OAUTH no cluster HUB
    name: openshift-hub
    placement:
      placementPath: input/hub-placement.yaml

  - description: Aplica políticas para configurar OAUTH em todos os clusters
    name: openshift-clusters
    placement:
      placementPath: input/clusters-placement.yaml

  - description: Aplica políticas para configurar OAUTH no cluster de producao
    name: openshift-prd
    placement:
      placementPath: input/prd-placement.yaml